import type { Profile, Order, Settings, Notification, PortfolioProject, PortfolioSettings, ChatMessage, PortfolioBlock, Goal, Review, DayOff, WorkSchedule } from './types'

export const MOCK_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    sender_id: 'client-1',
    receiver_id: 'admin-1',
    content: 'Salut Fahim, on a besoin d\'une animation urgente pour la nouvelle vidéo.',
    read: true,
    created_at: '2026-03-25T10:00:00Z',
  },
  {
    id: 'msg-2',
    sender_id: 'admin-1',
    receiver_id: 'client-1',
    content: 'Salut ! Bien sûr, envoie le brief sur le dashboard et je te la sors pour demain soir.',
    read: true,
    created_at: '2026-03-25T10:15:00Z',
  },
  {
    id: 'msg-3',
    sender_id: 'client-2',
    receiver_id: 'admin-1',
    content: 'Le dernier rendu est parfait, le client a adoré !',
    read: false,
    created_at: new Date().toISOString(),
  }
]

export const MOCK_SETTINGS: Settings = {
  id: 'settings-1',
  price_per_second: 5.00,
  seconds_per_day: 30,
  updated_at: '2026-03-20T10:00:00Z',
}

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'admin-1',
    email: 'fahim@motionplanner.com',
    full_name: 'Fahim',
    company: 'Motion Studio',
    role: 'admin',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
  },
  {
    id: 'client-1',
    email: 'contact@fuze.fr',
    full_name: 'Fuze',
    company: 'Fuze',
    role: 'client',
    user_type: 'partner',
    specialty: 'agence',
    monthly_volume: '4-10',
    tools: ['Premiere Pro', 'After Effects'],
    created_at: '2026-02-01T09:00:00Z',
    updated_at: '2026-03-10T14:00:00Z',
  },
  {
    id: 'client-2',
    email: 'hatim@example.com',
    full_name: 'Hatim',
    company: 'Hatim Prod',
    role: 'client',
    user_type: 'partner',
    specialty: 'monteur',
    monthly_volume: '1-3',
    tools: ['Premiere Pro', 'DaVinci Resolve'],
    created_at: '2026-02-10T11:00:00Z',
    updated_at: '2026-03-15T09:00:00Z',
  },
  {
    id: 'client-3',
    email: 'hello@codealux.com',
    full_name: 'Codealux',
    company: 'Codealux',
    role: 'client',
    user_type: 'partner',
    specialty: 'freelance',
    monthly_volume: '4-10',
    tools: ['Premiere Pro', 'After Effects', 'Final Cut'],
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-20T16:00:00Z',
  },
  {
    id: 'client-4',
    email: 'contact@aebid.com',
    full_name: 'Aebid',
    company: 'Aebid Corp',
    role: 'client',
    user_type: 'partner',
    specialty: 'realisateur',
    monthly_volume: '1-3',
    tools: ['DaVinci Resolve', 'After Effects'],
    created_at: '2026-03-05T10:00:00Z',
    updated_at: '2026-03-20T16:00:00Z',
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-1',
    client_id: 'client-1',
    client_name: 'TechCorp',
    project_name: 'Intro YouTube TechCorp',
    description: 'Animation d\'intro pour la chaîne YouTube de TechCorp. Style moderne avec logo reveal et particules.',
    seconds_ordered: 15,
    price_per_second: 5,
    total_price: 75,
    production_days: 1,
    deadline: '2026-04-01',
    status: 'completed',
    scheduled_start: '2026-03-17',
    scheduled_end: '2026-03-17',
    admin_notes: 'Livré en avance',
    created_at: '2026-03-10T09:00:00Z',
    updated_at: '2026-03-17T17:00:00Z',
  },
  {
    id: 'order-2',
    client_id: 'client-1',
    client_name: 'FoodieApp',
    project_name: 'Vidéo promo FoodieApp',
    description: 'Motion design pour publicité réseaux sociaux. Animations de plats, transitions fluides, call-to-action.',
    seconds_ordered: 45,
    price_per_second: 5,
    total_price: 225,
    production_days: 2,
    deadline: '2026-04-10',
    status: 'in_progress',
    scheduled_start: '2026-03-24',
    scheduled_end: '2026-03-25',
    admin_notes: '',
    created_at: '2026-03-15T14:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
  },
  {
    id: 'order-3',
    client_id: 'client-2',
    client_name: 'EcoVert',
    project_name: 'Présentation corporate EcoVert',
    description: 'Vidéo de présentation d\'entreprise avec infographies animées, graphiques et données clés.',
    seconds_ordered: 90,
    price_per_second: 5,
    total_price: 450,
    production_days: 3,
    deadline: '2026-04-15',
    status: 'in_progress',
    scheduled_start: '2026-03-26',
    scheduled_end: '2026-03-28',
    admin_notes: 'Client prioritaire',
    created_at: '2026-03-12T10:00:00Z',
    updated_at: '2026-03-20T11:00:00Z',
  },
  {
    id: 'order-4',
    client_id: 'client-2',
    client_name: 'StartupXYZ',
    project_name: 'Explainer video StartupXYZ',
    description: 'Vidéo explicative de 2 minutes pour lever de fonds. Style flat design avec personnages.',
    seconds_ordered: 120,
    price_per_second: 5,
    total_price: 600,
    production_days: 4,
    deadline: '2026-04-30',
    status: 'pending',
    scheduled_start: null,
    scheduled_end: null,
    admin_notes: '',
    created_at: '2026-03-20T08:00:00Z',
    updated_at: '2026-03-20T08:00:00Z',
  },
  {
    id: 'order-5',
    client_id: 'client-3',
    client_name: 'GymFit',
    project_name: 'Teaser ouverture GymFit',
    description: 'Teaser dynamique pour l\'ouverture d\'une nouvelle salle de sport. Effets énergiques et musique intense.',
    seconds_ordered: 30,
    price_per_second: 5,
    total_price: 150,
    production_days: 1,
    deadline: '2026-04-05',
    status: 'pending',
    scheduled_start: null,
    scheduled_end: null,
    admin_notes: '',
    created_at: '2026-03-22T16:00:00Z',
    updated_at: '2026-03-22T16:00:00Z',
  },
  {
    id: 'order-6',
    client_id: 'client-3',
    client_name: 'MaisonDeco',
    project_name: 'Catalogue animé MaisonDeco',
    description: 'Animations de transition pour catalogue de meubles en vidéo. Zooms, rotations 3D, textes animés.',
    seconds_ordered: 60,
    price_per_second: 5,
    total_price: 300,
    production_days: 2,
    deadline: null,
    status: 'rejected',
    scheduled_start: null,
    scheduled_end: null,
    admin_notes: 'Budget insuffisant, à revoir',
    created_at: '2026-03-18T13:00:00Z',
    updated_at: '2026-03-19T09:00:00Z',
  },
]

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    user_id: 'client-1',
    title: 'Commande acceptée',
    message: 'Votre commande "Vidéo promo FoodieApp" a été acceptée et est en cours de production.',
    read: false,
    order_id: 'order-2',
    created_at: '2026-03-20T10:00:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'client-1',
    title: 'Commande terminée',
    message: 'Votre commande "Intro YouTube TechCorp" est terminée !',
    read: true,
    order_id: 'order-1',
    created_at: '2026-03-17T17:00:00Z',
  },
  {
    id: 'notif-3',
    user_id: 'client-2',
    title: 'Commande acceptée',
    message: 'Votre commande "Présentation corporate EcoVert" a été acceptée.',
    read: false,
    order_id: 'order-3',
    created_at: '2026-03-20T11:00:00Z',
  },
  {
    id: 'notif-4',
    user_id: 'client-3',
    title: 'Commande refusée',
    message: 'Votre commande "Catalogue animé MaisonDeco" a été refusée.',
    read: true,
    order_id: 'order-6',
    created_at: '2026-03-19T09:00:00Z',
  },
]

export const MOCK_GOALS: Goal[] = [
  {
    id: 'goal-1',
    user_id: 'admin-1',
    title: 'Objectif mensuel',
    target_seconds: 500,
    period: 'monthly',
    created_at: '2026-03-01T00:00:00Z',
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'review-1',
    client_id: 'client-1',
    client_name: 'Fuze',
    order_id: 'order-1',
    project_name: 'Intro YouTube TechCorp',
    content: 'Le rendu est incroyable, le client a adoré l\'animation. Livraison rapide et communication parfaite.',
    rating: 5,
    created_at: '2026-03-18T10:00:00Z',
  },
  {
    id: 'review-2',
    client_id: 'client-2',
    client_name: 'Hatim',
    order_id: 'order-3',
    project_name: 'Présentation corporate EcoVert',
    content: 'Très bon travail sur les infographies animées. Le style correspond exactement au brief.',
    rating: 4,
    created_at: '2026-03-22T14:00:00Z',
  },
  {
    id: 'review-3',
    client_id: 'client-3',
    client_name: 'Codealux',
    order_id: null,
    project_name: 'Projet général',
    content: 'Collaboration top depuis le début, je recommande à 100%. Qualité pro et délais respectés.',
    rating: 5,
    created_at: '2026-03-25T09:00:00Z',
  },
]

export const MOCK_DAYS_OFF: DayOff[] = [
  { id: 'dayoff-1', date: '2026-04-06', label: 'Lundi de Pâques', created_at: '2026-03-01T00:00:00Z' },
  { id: 'dayoff-2', date: '2026-05-01', label: 'Fête du travail', created_at: '2026-03-01T00:00:00Z' },
  { id: 'dayoff-3', date: '2026-04-10', label: 'Perso', created_at: '2026-03-20T00:00:00Z' },
]

export const MOCK_WORK_SCHEDULE: WorkSchedule[] = [
  { id: 'ws-0', day_of_week: 0, is_working: false, start_hour: '09:00', end_hour: '18:00' },
  { id: 'ws-1', day_of_week: 1, is_working: true, start_hour: '09:00', end_hour: '18:00' },
  { id: 'ws-2', day_of_week: 2, is_working: true, start_hour: '09:00', end_hour: '18:00' },
  { id: 'ws-3', day_of_week: 3, is_working: true, start_hour: '09:00', end_hour: '18:00' },
  { id: 'ws-4', day_of_week: 4, is_working: true, start_hour: '09:00', end_hour: '18:00' },
  { id: 'ws-5', day_of_week: 5, is_working: true, start_hour: '09:00', end_hour: '18:00' },
  { id: 'ws-6', day_of_week: 6, is_working: false, start_hour: '09:00', end_hour: '18:00' },
]

export const MOCK_PORTFOLIO_SETTINGS: PortfolioSettings = {
  background_color: '#111827',
  ambient_music_url: null,
  hero_title: 'Travaux Récents.',
  hero_subtitle: 'Un aperçu des projets Motion Design réalisés en marque blanche pour nos partenaires.',
  cta_text: 'Déléguer mon premier projet',
  cta_url: '/setup',
}

export const MOCK_PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    id: 'proj-1',
    title: 'Campagne Nike Air',
    category: 'Publicité 3D',
    client: 'Fuze',
    media_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop',
    media_type: 'image',
    format: 'long',
    created_at: new Date().toISOString(),
    description: 'Animation 3D pour la campagne Nike Air Max. Rendu photoréaliste, tracking caméra et particules.',
    duration_seconds: 30,
    software_used: ['After Effects', 'Blender', 'Cinema 4D'],
    audience: 'Grand public',
    style: '3D Cinématique',
    before_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2000&auto=format&fit=crop',
    views: 284000,
    likes: 12400,
    watch_time_avg: 24,
    ctr: 8.7,
    retention_rate: 78,
    platform: 'YouTube',
  },
  {
    id: 'proj-2',
    title: 'Short Tiktok Viral',
    category: 'Motion App',
    client: 'Codealux',
    media_url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=2000&auto=format&fit=crop',
    media_type: 'image',
    format: 'short',
    created_at: new Date().toISOString(),
    description: 'Motion design dynamique pour contenu TikTok viral. Animations rapides, textes animés.',
    duration_seconds: 15,
    software_used: ['After Effects', 'Premiere Pro'],
    audience: 'Gen Z',
    style: 'Kinetic Typography',
    views: 1200000,
    likes: 89000,
    watch_time_avg: 13,
    ctr: 12.3,
    retention_rate: 92,
    platform: 'TikTok',
  },
  {
    id: 'proj-3',
    title: 'Explicatif Crypto Web3',
    category: '2D Flat',
    client: 'Aebid',
    media_url: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=2832&auto=format&fit=crop',
    media_type: 'image',
    format: 'long',
    created_at: new Date().toISOString(),
    description: 'Vidéo explicative pour projet crypto. Infographies animées, graphiques et iconographie flat design.',
    duration_seconds: 120,
    software_used: ['After Effects', 'Illustrator'],
    audience: 'B2B Tech',
    style: 'Flat Design',
    before_url: 'https://images.unsplash.com/photo-1622630998477-20aa696ecb05?q=80&w=2000&auto=format&fit=crop',
    views: 47000,
    likes: 3200,
    watch_time_avg: 68,
    ctr: 5.4,
    retention_rate: 56,
    platform: 'YouTube',
  },
  {
    id: 'proj-4',
    title: 'Reel Instagram Mode',
    category: 'Motion Social',
    client: 'Fuze',
    media_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?q=80&w=2000&auto=format&fit=crop',
    media_type: 'image',
    format: 'short',
    created_at: new Date().toISOString(),
    description: 'Reel Instagram pour une marque de mode streetwear. Montage cut rapide, overlays texte, color grading.',
    duration_seconds: 22,
    software_used: ['Premiere Pro', 'After Effects'],
    audience: 'Grand public',
    style: 'Kinetic Typography',
    views: 530000,
    likes: 41000,
    watch_time_avg: 19,
    ctr: 9.8,
    retention_rate: 85,
    platform: 'Instagram',
  },
  {
    id: 'proj-5',
    title: 'Spot TV Automobile',
    category: 'Publicité 3D',
    client: 'Aebid',
    media_url: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=2000&auto=format&fit=crop',
    media_type: 'image',
    format: 'long',
    created_at: new Date().toISOString(),
    description: 'Spot publicitaire 3D photoréaliste pour constructeur automobile. Tracking caméra, particules, HDR.',
    duration_seconds: 45,
    software_used: ['Cinema 4D', 'After Effects', 'DaVinci Resolve'],
    audience: 'Grand public',
    style: '3D Cinématique',
    views: 1800000,
    likes: 67000,
    watch_time_avg: 38,
    ctr: 11.2,
    retention_rate: 82,
    platform: 'YouTube',
  },
]

export const MOCK_PORTFOLIO_BLOCKS: PortfolioBlock[] = [
  {
    id: 'block-showreel',
    type: 'showreel',
    enabled: true,
    order: 0,
    config: { clip_duration_seconds: 3, transition_style: 'crossfade', project_ids: [] },
  },
  {
    id: 'block-filters',
    type: 'filters',
    enabled: true,
    order: 1,
    config: { enabled_filters: ['type', 'format', 'style', 'software'] },
  },
  {
    id: 'block-before-after',
    type: 'before_after',
    enabled: true,
    order: 2,
    config: {
      items: [
        { id: 'ba-1', project_id: 'proj-1', before_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2000&auto=format&fit=crop', after_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop', label: 'Campagne Nike Air' },
        { id: 'ba-2', project_id: 'proj-3', before_url: 'https://images.unsplash.com/photo-1622630998477-20aa696ecb05?q=80&w=2000&auto=format&fit=crop', after_url: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=2832&auto=format&fit=crop', label: 'Explicatif Crypto' },
      ]
    },
  },
  {
    id: 'block-testimonial',
    type: 'testimonial',
    enabled: true,
    order: 3,
    config: {
      testimonials: [
        { id: 'test-1', project_id: 'proj-1', client_name: 'Julien', client_photo_url: '', client_role: 'Directeur Créatif — Fuze', quote: 'Le rendu 3D de la campagne Nike a dépassé nos attentes. Le client nous a recommandé 3 fois depuis.', scores: [{ label: 'Créativité', value: 5 }, { label: 'Délais', value: 5 }, { label: 'Communication', value: 4 }] },
        { id: 'test-2', project_id: 'proj-2', client_name: 'Samir', client_photo_url: '', client_role: 'CEO — Codealux', quote: 'Les shorts TikTok ont généré +200K vues en 48h. Le style motion est exactement ce qu\'on cherchait.', scores: [{ label: 'Créativité', value: 5 }, { label: 'Délais', value: 4 }, { label: 'Communication', value: 5 }] },
      ]
    },
  },
  {
    id: 'block-tech-stack',
    type: 'tech_stack',
    enabled: true,
    order: 4,
    config: {
      tools: [
        { id: 'tool-1', name: 'After Effects', icon_url: '/ae.png', category: 'Compositing', proficiency: 5, project_count: 47 },
        { id: 'tool-2', name: 'Blender', icon_url: '/blender.png', category: '3D', proficiency: 4, project_count: 18 },
        { id: 'tool-3', name: 'Premiere Pro', icon_url: '/pr.png', category: 'Montage', proficiency: 5, project_count: 32 },
        { id: 'tool-4', name: 'Cinema 4D', icon_url: '', category: '3D', proficiency: 3, project_count: 8 },
        { id: 'tool-5', name: 'Illustrator', icon_url: '', category: 'Design', proficiency: 4, project_count: 24 },
      ]
    },
  },
  {
    id: 'block-availability',
    type: 'availability_widget',
    enabled: true,
    order: 5,
    config: { status: 'available', next_available_date: '2026-04-01', average_delivery_days: 5, message: 'Disponible pour de nouveaux projets' },
  },
]
